# .woodpecker/dadjoke-viewer.yml
steps:
  setup:
    image: node:20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  run-tests:
    image: node:20
    commands:
      - echo "Running Pact consumer tests..."
      - npm run test:pact

  publish-pact:
    image: docker:latest
    environment:
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    commands:
      - echo "Publishing Pact contract to broker..."
      - |
        docker run --rm \
          -w /workspace \
          -v ${PWD}:${PWD} \
          -e PACT_BROKER_BASE_URL \
          pactfoundation/pact-cli:latest \
          publish \
          ${PWD}/pacts \
          --consumer-app-version "$(git rev-parse --short HEAD)" \
          --tag-with-git-branch